# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'JSONParsingNonMVC' do
pod 'Alamofire', '~> 3.0'
end

target 'JSONParsingNonMVCTests' do

end

target 'JSONParsingNonMVCUITests' do

end

